apiVersion: v1
kind: Service
metadata:
  name: postgresdb 
  labels:
    app: postgresdb 
spec:
  type: NodePort 
  ports:
  - targetPort: 5432
    port: 5432
    nodePort: 30001
    protocol: TCP
  selector:
    app: postgresdb