apiVersion: v1
kind: Service
metadata:
  name: studentdb-svc 
  labels:
    app: studentdb 
spec:
  type: NodePort 
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 31000
    protocol: TCP
  selector:
    app: studentdb